version: '3'

services:

  netconf-server:
    container_name: netconf-server
    image: onap/org.onap.integration.simulators.netconf-server:latest
    environment:
     - ENABLE_TLS=true
    ports:
     - "830:830"
     - "6513:6513"
